spring.application.name=ToDoApplication

# MySQL ?????
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://161.33.213.143:3306/todo_application?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tokyo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tioplate}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chen36631489}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Redis ??
spring.data.redis.host=${SPRING_REDIS_HOST:161.33.213.143}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
# spring.data.redis.password=  # ????????
spring.data.redis.database=0
spring.data.redis.timeout=3000ms

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5174,http://127.0.0.1:5174}
